FROM henriquej0904/hyflexchain:base-tc

WORKDIR /app

RUN echo "security.provider.13=org.bouncycastle.jce.provider.BouncyCastleProvider" >> /usr/lib/jvm/java-19-openjdk-amd64/conf/security/java.security

COPY target/Blockmess-Wrapper-Server-1.0-SNAPSHOT-jar-with-dependencies.jar /app/app.jar

# ENTRYPOINT ["java", "-cp", "app.jar"]
