package pt.unl.fct.di.hyflexchain.planes.consensus.committees;

/**
 * Represents the criteria used to elect a specific
 * committee for a consensus mechanism.
 * 
 * @param size Committee cardinality
 * @param randSource The type of randomness source used to elect a committee
 */
public record CommitteeElectionCriteria(
	int size,
	RandSource randSource/**,
	committee validity criteria */
) {
	
	/**
	 * The type of randomness source used to elect a committee.
	 */
	public static enum RandSource
	{
		/**
		 * Randomness based on a local approach where each node
		 * computes a deterministic function to obtain a random seed.
		 */
		LOCAL_RAND,

		/**
		 * Randomness based on a Distributed/Decentralized approach
		 * where a random seed is generated by specialized nodes with
		 * security guarantees.
		 */
		DRAND
	}

	

}
