package pt.unl.fct.di.hyflexchain.planes.consensus.committees;

/**
 * Represents the criteria used to elect a specific
 * committee for a consensus mechanism.
 * 
 * @param size Max size of the committee
 * @param sizeThreshold The min number of active participants
 * to be able to execute the committee functions
 * @param randSource The type of randomness source used to elect a committee
 * @param validity An object to verify if a committee is still valid to be used.
 */
public record CommitteeElectionCriteria(
	int size,
	int sizeThreshold,
	RandSource randSource,
	CommitteeValidity validity
) {
	
	/**
	 * The type of randomness source used to elect a committee.
	 */
	public static enum RandSource
	{
		/**
		 * Randomness based on a local approach where each node
		 * computes a deterministic function to obtain a random seed.
		 */
		LOCAL_RAND,

		/**
		 * Randomness based on a Distributed/Decentralized approach
		 * where a random seed is generated by specialized nodes with
		 * security guarantees.
		 */
		DRAND
	}

	

}
